name: crypto_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dynamic_color: ^1.6.9
  flutter:
    sdk: flutter
  http: ^1.1.2
  intl: ^0.19.0
  realm: ^1.6.1
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
